package enrich

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/dev-manul/kartograf/internal/core/store"
)

// phpstanRule is the PHPStan rule that exports resolved call edges.
// It is scaffolded into <root>/.kartograf/phpstan/ and registered via
// the generated neon config which includes the project's own
// phpstan.neon (so autoloading, paths and stub files match the
// project's setup exactly).
//
// Edges are emitted as analysis "errors" with the identifier
// kartograf.edge and a JSON payload as the message. That rides
// PHPStan's result cache: unchanged files replay their cached edges,
// so repeat runs are incremental.
const phpstanRule = `<?php

declare(strict_types=1);

namespace Kartograf;

use PhpParser\Node;
use PHPStan\Analyser\Scope;
use PHPStan\Reflection\ReflectionProvider;
use PHPStan\Rules\Rule;
use PHPStan\Rules\RuleErrorBuilder;

/**
 * Emits type-inferred call edges as pseudo-errors (identifier
 * kartograf.edge, message = JSON payload) for kartograf to collect
 * from the JSON error output.
 *
 * Generated by kartograf — do not edit (regenerated on every
 * "kartograf enrich php" run).
 *
 * @implements Rule<Node\Expr>
 */
final class KartografExportRule implements Rule
{
    public function __construct(private ReflectionProvider $reflectionProvider)
    {
    }

    public function getNodeType(): string
    {
        return Node\Expr::class;
    }

    public function processNode(Node $node, Scope $scope): array
    {
        $edges = [];
        if ($node instanceof Node\Expr\MethodCall || $node instanceof Node\Expr\NullsafeMethodCall) {
            if (!$node->name instanceof Node\Identifier) {
                return [];
            }
            $method = $node->name->toString();
            foreach ($scope->getType($node->var)->getObjectClassReflections() as $cls) {
                if (!$cls->hasMethod($method)) {
                    continue;
                }
                $declaring = $cls->getMethod($method, $scope)->getDeclaringClass()->getName();
                $edges[] = $this->edge($scope, 'calls', $declaring . '::' . $method . '()', $node->getStartLine());
            }
        } elseif ($node instanceof Node\Expr\StaticCall) {
            if (!$node->name instanceof Node\Identifier || !$node->class instanceof Node\Name) {
                return [];
            }
            $method = $node->name->toString();
            $className = $scope->resolveName($node->class);
            if ($this->reflectionProvider->hasClass($className)) {
                $cls = $this->reflectionProvider->getClass($className);
                if ($cls->hasMethod($method)) {
                    $className = $cls->getMethod($method, $scope)->getDeclaringClass()->getName();
                }
            }
            $edges[] = $this->edge($scope, 'calls', $className . '::' . $method . '()', $node->getStartLine());
        } elseif ($node instanceof Node\Expr\New_) {
            if ($node->class instanceof Node\Name) {
                $edges[] = $this->edge($scope, 'instantiates', $scope->resolveName($node->class), $node->getStartLine());
            }
        }

        return array_values(array_filter($edges));
    }

    private function edge(Scope $scope, string $kind, string $to, int $line): ?\PHPStan\Rules\IdentifierRuleError
    {
        $from = '';
        $func = $scope->getFunction();
        if ($func !== null) {
            $cls = $scope->getClassReflection();
            $from = $cls !== null
                ? $cls->getName() . '::' . $func->getName() . '()'
                : $func->getName() . '()';
        }
        $payload = json_encode(
            ['from' => $from, 'kind' => $kind, 'to' => $to],
            JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
        if ($payload === false) {
            return null;
        }

        return RuleErrorBuilder::message($payload)
            ->identifier('kartograf.edge')
            ->line($line)
            ->build();
    }
}
`

const phpstanNeon = `# Generated by kartograf — do not edit.
# Runs the project's own phpstan config plus the kartograf edge
# exporter (registered via --autoload-file on the CLI).
includes:
    - %s

services:
    -
        class: Kartograf\KartografExportRule
        tags: [phpstan.rules.rule]
`

// ScaffoldPHP writes the PHPStan rule and config into
// <root>/.kartograf/phpstan/. projectNeon is the path to the
// project's own phpstan config (absolute or root-relative).
func ScaffoldPHP(root, projectNeon string) (configPath string, err error) {
	dir := filepath.Join(root, Dir, "phpstan")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	if !filepath.IsAbs(projectNeon) {
		projectNeon = filepath.Join(root, projectNeon)
	}
	if err := os.WriteFile(filepath.Join(dir, "KartografExportRule.php"), []byte(phpstanRule), 0o644); err != nil {
		return "", err
	}
	configPath = filepath.Join(dir, "kartograf.neon")
	neon := fmt.Sprintf(phpstanNeon, projectNeon)
	return configPath, os.WriteFile(configPath, []byte(neon), 0o644)
}

// FindPHPStan locates the project's phpstan binary (vendor/bin at the
// root or one directory below).
func FindPHPStan(root string) string {
	candidates, _ := filepath.Glob(filepath.Join(root, "*", "vendor", "bin", "phpstan"))
	if direct := filepath.Join(root, "vendor", "bin", "phpstan"); fileExists(direct) {
		return direct
	}
	if len(candidates) > 0 {
		return candidates[0]
	}
	return ""
}

// FindProjectNeon locates the project's own phpstan config.
func FindProjectNeon(root string) string {
	for _, name := range []string{"phpstan.neon", "phpstan.neon.dist", "phpstan.dist.neon"} {
		if fileExists(filepath.Join(root, name)) {
			return filepath.Join(root, name)
		}
	}
	return ""
}

func fileExists(p string) bool {
	fi, err := os.Stat(p)
	return err == nil && !fi.IsDir()
}

// RunPHPStan executes the analysis with the exporter rule registered
// and returns the edges parsed from the JSON error output. A non-zero
// exit code alone is fine (the project's own findings are not our
// concern). PHPStan's result cache makes repeat runs incremental:
// cached files replay their kartograf.edge pseudo-errors.
func RunPHPStan(root, phpstanBin, configPath string, memLimit string, logf func(format string, args ...any)) ([]store.ExtEdge, error) {
	rulePath := filepath.Join(filepath.Dir(configPath), "KartografExportRule.php")
	cmd := exec.Command("php", phpstanBin, "analyse",
		"--configuration", configPath,
		"--autoload-file", rulePath,
		"--no-progress", "--error-format", "json",
		"--memory-limit", memLimit)
	cmd.Dir = root
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	runErr := cmd.Run()

	edges, parseErr := parsePHPStanJSON(stdout.Bytes())
	if parseErr != nil {
		if runErr != nil {
			return nil, fmt.Errorf("phpstan failed: %v: %s", runErr,
				truncate(stderr.String()+stdout.String(), 600))
		}
		return nil, parseErr
	}
	if runErr != nil {
		logf("enrich(php): phpstan exited non-zero (project findings ignored)")
	}
	return edges, nil
}

// ParsePHPStanJSONFile extracts edges from a raw PHPStan
// --error-format=json output captured elsewhere (docker, CI).
func ParsePHPStanJSONFile(path string) ([]store.ExtEdge, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	return parsePHPStanJSON(data)
}

// parsePHPStanJSON extracts kartograf.edge pseudo-errors from
// PHPStan's --error-format=json output.
func parsePHPStanJSON(data []byte) ([]store.ExtEdge, error) {
	var out struct {
		Files map[string]struct {
			Messages []struct {
				Message    string `json:"message"`
				Line       int    `json:"line"`
				Identifier string `json:"identifier"`
			} `json:"messages"`
		} `json:"files"`
	}
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, fmt.Errorf("parse phpstan json output: %w", err)
	}
	var edges []store.ExtEdge
	for file, f := range out.Files {
		for _, m := range f.Messages {
			if m.Identifier != "kartograf.edge" {
				continue
			}
			var e store.ExtEdge
			if err := json.Unmarshal([]byte(m.Message), &e); err != nil {
				continue
			}
			e.File = file
			e.Line = m.Line
			edges = append(edges, e)
		}
	}
	return edges, nil
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "…"
}
